source $HOME/.oh-my-zshrc

alias vim=nvim

alias g=git
alias gs='g status'
alias gch='g checkout'
alias gb='git branch'
alias gbd='gb -D'
alias gr='g reset'
alias gl='g log'
alias ga='g add'
alias gd='g diff'
alias gc='g commit'
alias gcm='gc -m'
alias gca='gc --amend'

